### ISSUE TITLE
issue with uploading a new (initial) dataset (100 files) with wildcard

### ISSUE THREAD

**Issue by ekfallon** [dafnifacility/cli#113] opened 2023-08-10 11:06 UTC
SSL error when I try to upload a new initial dataset with the dataset upload command using a wildcard to read ~100 files from a folder I have locally. Error messages attached. I have double checked and all my packages match the requirements.txt on the CLI github including:

certifi==2023.7.22
charset-normalizer==3.2.0
click==8.1.6
idna==3.4
python-dateutil==2.8.2
requests==2.31.0
six==1.16.0
tabulate==0.9.0
tqdm==4.65.0
urllib3==2.0.4

My colleague David Pritchard has had the same issue (we both work for the same organisation)

![SSLerror](https://github.com/dafnifacility/cli/assets/76099325/79379f3a-d706-4302-a23a-8d952b3b74ba)

**Comment by joelvdavies** [comment] 2023-08-10 14:51
Thanks for reporting this. I am currently unable to recreate it, does the error appear when uploading a single file as well or is it just with the 100? Also what size are the files?

**Comment by ekfallon** [comment] 2023-08-10 16:40
Thanks for your help! David was able to upload a dataset with a couple of files - individually pointing to them rather than using the wildcard. Sorry, it was actually 300 files, not 100. Each file is around 23 MB. We tried on different days - days apart from each other

**Comment by joelvdavies** [comment] 2023-08-11 09:16
Wildcards should work, I have tested it with ~300 files on command prompt, PowerShell and terminal. From the error message it does seem to be an issue with the first file it uploads and it doesn’t look like its picked up anything it shouldn’t have either. So my current guess is that it must have been temperamental at the times you both tried (even though it feels unlikely to me to have happened twice) as there shouldn’t to my knowledge be any difference between uploading 300 files with it failing on the first and uploading a few files individually.
Would you be able to try uploading the large number of files using wildcards again just as a test, and if it fails perhaps wait a while and try again? I would like to be sure it was not just being temperamental.

**Comment by ekfallon** [comment] 2023-08-16 08:33
Hi @joelvdavies, Thanks so much for your help! Just a note to say that I have followed the same process as David above and have the exact same error unfortunately!

**Comment by joelvdavies** [comment] 2023-08-17 13:12
@ekfallon @davidpritchard1  I have just released another version which will hopefully mitigate this issue, could you upgrade the package e.g. with `pip install --pre --upgrade dafni-cli` and then try again please.

**Comment by davidpritchard1** [comment] 2023-08-18 10:56
Hi @joelvdavies, thanks very much for looking at a workaround for this. I've tried again a few times, but I still seem to be running into issues. The upload gets to the same degree of progress as before and then I can see it retrying a few times before the error is raised. On one of the tries I took the file that it is stopping on out of the folder, but this didn't help (so probably not an issue with the file I presume). Sometimes if I try one attempt quickly after the previous one it seems to make a little bit less progress before running into the error.

```
Retrieving file upload URls
Uploading files
WRM_baseline_100_paramset1.txt: 100%|██████████████████████████████████████████████| 22.5M/22.5M [00:24<00:00, 977kB/s]
WRM_baseline_10_paramset1.txt: 100%|██████████████████████████████████████████████| 22.6M/22.6M [00:22<00:00, 1.06MB/s]
WRM_baseline_11_paramset1.txt: 100%|██████████████████████████████████████████████| 22.5M/22.5M [00:22<00:00, 1.06MB/s]
WRM_baseline_12_paramset1.txt: 100%|██████████████████████████████████████████████| 22.6M/22.6M [00:22<00:00, 1.06MB/s]
WRM_baseline_13_paramset1.txt: 100%|██████████████████████████████████████████████| 22.6M/22.6M [00:22<00:00, 1.05MB/s]
WRM_baseline_14_paramset1.txt: 100%|██████████████████████████████████████████████| 22.6M/22.6M [00:22<00:00, 1.05MB/s]
WRM_baseline_15_paramset1.txt: 100%|██████████████████████████████████████████████| 22.5M/22.5M [00:22<00:00, 1.05MB/s]
WRM_baseline_16_paramset1.txt: 100%|██████████████████████████████████████████████| 22.6M/22.6M [00:22<00:00, 1.06MB/s]
WRM_baseline_17_paramset1.txt: 100%|██████████████████████████████████████████████| 22.5M/22.5M [00:22<00:00, 1.06MB/s]
WRM_baseline_18_paramset1.txt: 100%|██████████████████████████████████████████████| 22.6M/22.6M [00:22<00:00, 1.06MB/s]
WRM_baseline_19_paramset1.txt: 100%|██████████████████████████████████████████████| 22.6M/22.6M [00:22<00:00, 1.06MB/s]
WRM_baseline_1_paramset1.txt: 100%|███████████████████████████████████████████████| 22.5M/22.5M [00:22<00:00, 1.06MB/s]
WRM_baseline_20_paramset1.txt: 100%|██████████████████████████████████████████████| 22.6M/22.6M [00:22<00:00, 1.05MB/s]
WRM_baseline_21_paramset1.txt: 100%|██████████████████████████████████████████████| 22.6M/22.6M [00:22<00:00, 1.05MB/s]
WRM_baseline_22_paramset1.txt:   0%|▏                                              | 80.0k/22.6M [00:00<02:10, 181kB/s]
Overall progress 14/200:   7%|███▋                                               | 316M/4.33G [05:20<1:09:37, 1.03MB/s]
Deleting temporary bucket
urllib3.exceptions.SSLError: EOF occurred in violation of protocol (_ssl.c:2423)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\DPRITCHARD01\AppData\Local\miniconda3\envs\cli1\Lib\site-packages\requests\adapters.py", line 486, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "C:\Users\DPRITCHARD01\AppData\Local\miniconda3\envs\cli1\Lib\site-packages\urllib3\connectionpool.py", line 844, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "C:\Users\DPRITCHARD01\AppData\Local\miniconda3\envs\cli1\Lib\site-packages\urllib3\util\retry.py", line 515, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='minio.secure.dafni.rl.ac.uk', port=443): Max retries exceeded with url: /58a860b3-0895-4a58-825f-19ced255d71f/WRM_baseline_22_paramset1.txt?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=ZAGGGNVQMEUKNAUJXHHX%2F20230818%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20230818T100101Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-Amz-Signature=b2a8f13198c42e4ff4696fcc4f263a86bd8cafae3aab654bc441e9c83b278744 (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:2423)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\DPRITCHARD01\AppData\Local\miniconda3\envs\cli1\Lib\site-packages\dafni_cli\api\session.py", line 366, in _authenticated_request
    response = requests.request(
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\DPRITCHARD01\AppData\Local\miniconda3\envs\cli1\Lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DPRITCHARD01\AppData\Local\miniconda3\envs\cli1\Lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DPRITCHARD01\AppData\Local\miniconda3\envs\cli1\Lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DPRITCHARD01\AppData\Local\miniconda3\envs\cli1\Lib\site-packages\requests\adapters.py", line 517, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='minio.secure.dafni.rl.ac.uk', port=443): Max retries exceeded with url: /58a860b3-0895-4a58-825f-19ced255d71f/WRM_baseline_22_paramset1.txt?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=ZAGGGNVQMEUKNAUJXHHX%2F20230818%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20230818T100101Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-Amz-Signature=b2a8f13198c42e4ff4696fcc4f263a86bd8cafae3aab654bc441e9c83b278744 (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:2423)')))

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\DPRITCHARD01\AppData\Local\miniconda3\envs\cli1\Scripts\dafni.exe\__main__.py", line 7, in <module>
  File "C:\Users\DPRITCHARD01\AppData\Local\miniconda3\envs\cli1\Lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DPRITCHARD01\AppData\Local\miniconda3\envs\cli1\Lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "C:\Users\DPRITCHARD01\AppData\Local\miniconda3\envs\cli1\Lib\site-packages\click\core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DPRITCHARD01\AppData\Local\miniconda3\envs\cli1\Lib\site-packages\click\core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DPRITCHARD01\AppData\Local\miniconda3\envs\cli1\Lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DPRITCHARD01\AppData\Local\miniconda3\envs\cli1\Lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DPRITCHARD01\AppData\Local\miniconda3\envs\cli1\Lib\site-packages\click\decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DPRITCHARD01\AppData\Local\miniconda3\envs\cli1\Lib\site-packages\dafni_cli\commands\upload.py", line 161, in dataset
    upload_dataset(ctx.obj["session"], metadata, files, json=json)
  File "C:\Users\DPRITCHARD01\AppData\Local\miniconda3\envs\cli1\Lib\site-packages\dafni_cli\datasets\dataset_upload.py", line 334, in upload_dataset
    upload_files(session, temp_bucket_id, file_paths, json=json)
  File "C:\Users\DPRITCHARD01\AppData\Local\miniconda3\envs\cli1\Lib\site-packages\dafni_cli\datasets\dataset_upload.py", line 262, in upload_files
    upload_file_to_minio(
  File "C:\Users\DPRITCHARD01\AppData\Local\miniconda3\envs\cli1\Lib\site-packages\dafni_cli\api\minio_api.py", line 48, in upload_file_to_minio
    return session.put_request(
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DPRITCHARD01\AppData\Local\miniconda3\envs\cli1\Lib\site-packages\dafni_cli\api\session.py", line 692, in put_request
    response = self._authenticated_request(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DPRITCHARD01\AppData\Local\miniconda3\envs\cli1\Lib\site-packages\dafni_cli\api\session.py", line 440, in _authenticated_request
    response = self._authenticated_request(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DPRITCHARD01\AppData\Local\miniconda3\envs\cli1\Lib\site-packages\dafni_cli\api\session.py", line 440, in _authenticated_request
    response = self._authenticated_request(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DPRITCHARD01\AppData\Local\miniconda3\envs\cli1\Lib\site-packages\dafni_cli\api\session.py", line 440, in _authenticated_request
    response = self._authenticated_request(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DPRITCHARD01\AppData\Local\miniconda3\envs\cli1\Lib\site-packages\dafni_cli\api\session.py", line 413, in _authenticated_request
    raise RuntimeError(
RuntimeError: Could not connect due to an SSLError after retrying 3 times
```

I could try on a different (non-work) computer at some point if it might help (I don't know if it could be something on our end?), but I'd need to copy the files across to do this (which I could do at some point next week).

**Comment by joelvdavies** [comment] 2023-08-18 12:06
@davidpritchard1 This is certainly a tricky one to diagnose, thanks for all the help. Yes I think it would be good to try it on a non-work computer at some point if you could, I have seen similar issues have been issues caused by VPNs & proxy settings so it would be good to rule out. There is also a different workaround I will have a look at and may try.

**Comment by davidpritchard1** [comment] 2023-08-18 14:25
Thanks @joelvdavies, I'll try on another computer next week and let you know how it goes.

**Comment by davidpritchard1** [comment] 2023-08-22 16:43
Hi @joelvdavies, I've just tried a couple of times on another (non-EA) computer and I ran into the same SSL error. It makes a similar amount of progress before the error occurs. So hopefully this means it isn't something to do with our work computers/IT at least!

**Comment by joelvdavies** [comment] 2023-08-23 07:56
Hi @davidpritchard1 Well that helps narrow it down at least! I have just added another potential fix and released it (as v0.0.1b3). Could you try that on any machine after upgrading again please.

**Comment by davidpritchard1** [comment] 2023-08-23 09:29
Hi @joelvdavies, thanks for releasing the new version. I've just upgraded and tried again, but I'm still running into the same issue unfortunately. It still only gets through about 14 of the 200 files before the error occurs (about 316 MB out of 4.33 GB). Very strange! I wonder if it'd be worth us sharing a part of this dataset with you (say the first 25 files, each about 22.6 MB) to see if you get the same error with the same data? If so I'd just need to check with my colleagues first in case we'd need to replace the data with "dummy numbers" (in which case I'd confirm that the dummy dataset gives the same error before sharing).

**Comment by joelvdavies** [comment] 2023-08-23 11:22
@davidpritchard1 Yes that would be great if you could – I am still unable to replicate it myself. If the latest version didn’t help then I guess it shouldn’t have anything to do with the number of files and rather something to do with those first ones. I can provide a one drive folder via email that you could upload them to if that would be useful. If they are uploadable via the front end you could also do that and email me the id – I should be able to download and reupload them again. It would also be interesting if the front-end works as I would expect it would fail at the same point.

**Comment by davidpritchard1** [comment] 2023-08-23 12:27
Hi @joelvdavies, I've just tried to upload the data a couple of times via the web interface and it did fail (looked to get to around 15% progress before failing, similar to the CLI). If you could share a folder to upload too please that'd be great.

**Comment by davidpritchard1** [comment] 2023-08-24 07:31
Hi @joelvdavies, thanks for sending the shared folder. I've uploaded the files now - there's 200 and they should all be a similar size (~22.5 MB), so if any are missing/too small etc just let me know.

**Comment by joelvdavies** [comment] 2023-08-24 13:29
Hi @davidpritchard1 ,
Thanks for sending over the files. I have downloaded them, verified that the CLI is attempting to upload them in the same order and the total size of files appears the same. While I did have an error on Windows it was a different error and was fixed by retrying the request as I tried with the SSLErrors. I also tried limiting my bandwidth down to the same speeds I can see in the screenshot above. Using ubuntu via WSL it worked just fine from the start. In short, I am still unable to recreate the issue.

There is this stackoverflow post that could be worth a shot for the CLI although none of the answers appear very conclusive https://stackoverflow.com/questions/33410577/python-requests-exceptions-sslerror-eof-occurred-in-violation-of-protocol

If that doesn’t work then my current thoughts are 
-	Could the upload then download (and unzipping) of the files from one drive have somehow modified the files in a way that fixed it? – You could verify this by redownloading the same files and trying to upload those
-	We could check the minio logs when this fails (provided we can act quickly enough after a failed attempt)

A colleague has also suggested that minio has been known to have issues when uploading a large number of files through the front-end which is sometimes resolved by using a different browser. So my suggestion would be to
-	Redownload the files from one drive – unzip them
-	Try to upload them via the CLI (potentially at a specific time/on a particular day so we are prepared)
-	If this fails – then notify me as soon as possible (ideally with the time you saw the error) and I will attempt to get the logs
-	If this succeeds, then you could try uploading via a different browser to the front end so we can hopefully get the broken files (although this is a longshot the website also failed before)

**Comment by joelvdavies** [comment] 2023-08-24 15:29
Hi @davidpritchard1. Thanks for this I have at last just managed to recreate it on my own pc, so it may not be necessary just yet. It looks like it may be down to the OpenSSL version, my pc is on 1.1.1t from February this year, and my laptop (both windows and wsl) are on 1.1.1l and 1.1.1f from 2021 and 2020 respectively. I will try and figure out how to resolve it there and hopefully come up with a solution.

**Comment by joelvdavies** [comment] 2023-08-25 10:11
Hi @davidpritchard1,
Thanks for all your help with this! I thought I would do a proper update now since I have had a chance to look at the issue more closely.

I definitely now believe the root cause is the OpenSSL version. It is strange that it is so intermittent as we would expect it to either always succeed or always fail and I can’t see anything in the release notes that would directly relate.

I have now discovered that at least for python for Windows, the OpenSSL version installed is tied to the python version, effectively meaning that any version past 3.9.4 appears to have the issue. On Linux I believe the version is independent of the python version but again I was running an older version about 2 years old. The minio version we are currently running is also a similar age so I believe the proper fix on our end is to update it.

In the meantime I thought of another potential workaround to try – as it appeared to me that after there was an issue uploading to a presigned url it kept failing whereas restarting the whole thing worked again. So I tried changing it to also get a new url when it fails and it appears to have done the trick. I tried the upload about 8 times yesterday and today have managed to upload 600 files ~ 12 GB. Going back to the old version its failing after about 80 files due to either the SSLEOFError or a seemingly related one ConnectionAbortedError depending on the python version I used.

For future reference the SSL version can be checked by running
```
import ssl
print(ssl.OPENSSL_VERSION)
```
So overall once my most recent PR has been merged I will release another version that hopefully 🤞 will fix it for you as well.

**Comment by davidpritchard1** [comment] 2023-08-25 10:35
Hi @joelvdavies, thanks very much for the update and explanation - really useful. It's great that you've been able to pinpoint the issue with OpenSSL. Fingers-crossed that the new version will do the trick - I'm around next week so can give it a try whenever it's ready.

**Comment by joelvdavies** [comment] 2023-08-25 13:02
@davidpritchard1 Just released as v0.0.1b4.

**Comment by joelvdavies** [comment] 2023-08-31 10:04
Hi Emily,
Thanks for confirming it works!

Could you create a separate issue for this please. The simple answer is no its not possible at the moment. I think there are two approaches for making this work though. The first is if I allow directories to be uploaded – this would require you to put the files into that folder structure yourself and then use the cli to upload the folder and the second is to allow you to enter that script as a parameter and use it to produce the filenames when the upload command runs. Is there any reason you would not be able to do the first? - This will help us decide which approach to take.

**Comment by ekfallon** [comment] 2023-08-31 10:11
Hi @joelvdavies,
Thanks again for your help!
We can definitely put the files into that folder structure ourselves (first approach), so if you could allow directories to be uploaded that would be perfect! Thank you!

**Closed** 2023-08-31 10:34 UTC
